### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by MarketingMaster** [soixantecircuits/wp-events-manager-importer#23]

**Comment by gabrielstuff** [comment]
What was the issue ?

Thanks

**Comment by MarketingMaster** [comment]
Sorry, I miss the plugin name. It was about
"events-manager-import-export-0.0.3-alpha".

https://wordpress.org/support/topic/event-manager-importer-stop-working-after-update

Thx, BR
Primož

2015-12-21 14:12 GMT+01.00, Gabriel notifications@github.com:

> What was the issue ?
> 
> Thanks
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/soixantecircuits/wp-events-manager-importer/issues/23#issuecomment-166302673

## 

*BR, *Marketing Master wwwmarketingmaster@gmail.com
